
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kouferka-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kouferka-app
  template:
    metadata:
      labels:
        app: kouferka-app
    spec:
      containers:
        - image: wil42/playground:v1
          name: kouferka-app
      ports:
        - containerPort: 8888
          name: http
          protocol: TCP
